Repository need4deed-org/website, pull requests merged in 2025-06, with the labels that each got.

#128 add: links
  src/components/FooterPartners/footer/ContactSocials.tsx
  src/components/VolunteeringCategories/Footer.tsx
  src/components/VolunteeringOpportunities/Footer.tsx
Labels: bug

#129 add: things
  src/App.tsx
  src/components/HeroSection/Content.tsx
  src/components/Layouts/staticPageLayout/StaticPageLayout.tsx
  src/components/RacSection/Content.tsx
  src/config/types.ts
  src/pages/GuidelinesPage.tsx
  src/pages/Landing.tsx
Labels: bug

#138 change the buggy word
  public/locales/de/translations.json
Labels: bug

#137 136 add language set from url param
  src/components/Layouts/staticPageLayout/PageWrapper.tsx
  src/components/Layouts/staticPageLayout/StaticPageLayout.tsx
  src/index.css
  src/pages/Landing.tsx
Labels: enhancement

#146 update: to more strict number validation
  src/components/forms/AddOpportunity/index.tsx
  src/components/forms/utils.ts
Labels: bug

#153 fix the bug
  src/components/styled/containers.tsx
Labels: bug

#151 51 discrepancies in opportunity cards
  .env.local.example
  public/locales/de/translations.json
  public/locales/en/translations.json
  src/components/OpportunityCards/index.tsx
  src/components/VolunteeringOpportunities/OpportunitiesForSection.tsx
  src/components/VolunteeringOpportunities/OpportunityCard.tsx
  src/components/VolunteeringOpportunities/OpportunityCardDetail.tsx
  src/components/VolunteeringOpportunities/OpportunityCardForGrid.tsx
  src/components/VolunteeringOpportunities/OpportunityCardPopup.tsx
  src/components/VolunteeringOpportunities/types.ts
  src/components/VolunteeringOpportunities/utils.ts
  src/index.css
  src/pages/Opportunities.tsx
  src/pages/Subpage.tsx
Labels: enhancement, refactor

#176 remove: unused file
  src/components/core/common/PageLayout.tsx
Labels: refactor

#180 156 fix event button
  src/components/HeaderNew/BurgerMenuItems.tsx
  src/components/HeaderNew/Header.tsx
  src/components/HeaderNew/MenuItems.tsx
  src/components/HeaderNew/MenuitemList.tsx
  src/config/types.ts
Labels: bug

#187 fix: concatenate both lists
  src/components/forms/BecomeVolunteer/index.tsx
Labels: bug

#191 Hotfix add opp filter ff
  src/components/OpportunityCards/FiltersButton.tsx
  src/config/constants.ts
Labels: bug
