Repository need4deed-org/website, pull requests merged in 2025-05, with the labels that each got.

#53 52 fix layout of modal before volunteer form
  public/locales/de/translations.json
  public/locales/en/translations.json
  src/components/forms/BecomeVolunteer/FillOrNotify.tsx
  src/components/forms/index.css
Labels: bug

#71 refactor: rename action and delete migration job
  .github/workflows/deploy.yml
Labels: refactor

#92 91 fix testimonial pic
  .env.local.example
  src/components/Testimonials/TestimonialCard.tsx
  src/hooks/api/useTestimonials.tsx
  src/hooks/api/utils.ts
  vite.config.ts
Labels: bug, refactor

#99 CarouselCard added
  src/components/ProcessSteps/CarouselCard.tsx
  src/components/ProcessSteps/ProcessStepsSection.tsx
  src/components/ProcessSteps/icon.tsx
  src/components/VolunteeringCategories/icon.tsx
  src/components/styled/containers.tsx
  src/components/styled/text.tsx
  src/components/svg/BulletDash.tsx
  src/index.css
Labels: enhancement

#115 90 copy changes on landing page german version
  public/locales/de/translations.json
  public/locales/en/translations.json
  src/components/core/button/Button/Button.tsx
  src/components/core/common/Activities.tsx
Labels: refactor
